apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv01
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /d/WorkSpace/K8s/share_drive/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop