apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  labels:
    k8s-app: kibana-logging
spec:
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30011
      protocol: TCP
  selector:
    k8s-app: kibana-logging
  type: NodePort
